var catalog = require( 'dw/catalog' );
var Logger = require('dw/system/Logger');

/*Script Modules*/
var TurnToHelper = require('int_turnto_core/cartridge/scripts/util/TurnToHelperUtil');
var CatalogWriterHelper = require('int_turnto_core/cartridge/scripts/util/CatalogWriterHelper');

//Globally scoped variables
var products;
var tempProduct;
var allowedLocales = TurnToHelper.getAllowedLocales();
var hashMapOfFileWriters;
 
//function is executed only ONCE
function beforeStep( parameters, stepExecution )
{
	try {
		if (parameters.IsDisabled) {
			return new Status(Status.OK, 'OK', 'Export Catalog job step is disabled.');
		}
		
		//instantiate new hash map to store the locale file writers
		hashMapOfFileWriters = CatalogWriterHelper.initializeFileWritersHashMap(allowedLocales);
		
		//query all site products
		products = catalog.ProductMgr.queryAllSiteProductsSorted();
	} catch (e) {
		Logger.error('ExportCatalog.js has failed on the beforeStep step with the following error: ' + e.message);
	}
}

//a function that returns the total number of items that are available, this function is called by the framework exactly once before chunk processing begins. A known total count allows better monitoring. 
//For example, to show that 50 of 100 items have already been processed.
function getTotalCount( parameters, stepExecution )
{
	//Return product count
	return products.count;
}

//the read function returns either one item or nothing. 
//It returns nothing if there are no more items available
function read( parameters, stepExecution )
{
	// Will strip out variant products from the catalog feed
	// IF "Use Variants" is set to "No"
	try {
		var useVariants = ServiceFactory.getUseVariantsPreference();
		//Return next product
		if( products && products.hasNext() ) {
			tempProduct = products.next();
			//do not return a product if use variants site preference is false and the product is a variant
			if (!useVariants && tempProduct.isVariant()) {
				return '';
			}
			return tempProduct;
		}
	} catch (e) {
		Logger.error('ExportCatalog.js has failed on the read step with the following error: ' + e.message);
	}
}

//It receives the item returned by the read function, performs a process, and returns one item
function process( product, parameters, stepExecution )
{
	if(empty(product)) {
		return '';
	}

	//Generate and return a simple mapping object with locale 
	//and formatted output such as ```{ "en_us": "Row data for English US", ...}``` 
	var json = {};
	try {
		//IMAGE
		var imageUrl = CatalogWriterHelper.getProductImageUrl(product);
		
		// PRICE
		var price : Money = product.getPriceModel().getPrice();
		var priceStr : String = price.getValue().toString();
	
		// CATEGORYPATHJSON
		var categoryPathJSON = CatalogWriterHelper.generateProductCategoryJson(product);
		
		// MEMBERS
		var bundledProductsArray : Collection = CatalogWriterHelper.getBundledProducts(product);
		
		// GTIN values
		var gtinHashMap = CatalogWriterHelper.getProductGtinHashMap(product);
		
		//CATEGORY
		//Leaving blank because CATEGORYPATHJSON is populated
		
		// Iterate though the SFCC locales configured for the current site, 
		// and get the relevant locale-based data
		allowedLocales.forEach(function (currentLocale) {
			//set the request to the current locale so localized attributes will be used
			request.setLocale(currentLocale);
				
			//KEYWORDS
			var keywords = '';
			if (product.getPageKeywords()) {
				keywords = product.getPageKeywords();
			}
			
			var localeJson = CatalogWriterHelper.generateLocaleJson(product, imageUrl, priceStr, price, categoryPathJSON, bundledProductsArray, gtinHashMap, keywords);
	
			//add localeJSON to full JSON
			json[currentLocale] = localeJson;
		});

	} catch (e) {
		Logger.error('ExportCatalog.js has failed on the process step with the following error: ' + e.message);
	}
	return json;
}

// Loop through the locales for the current site, retrieve the catalog feed content 
// generated by the "process" function, and write it to the appropriate locale file
function write( json, parameters, stepExecution )
{
	try {
		allowedLocales.forEach(function (currentLocale) {
			//retrieve the current file writer
			var localeFileWriter = hashMapOfFileWriters.get(currentLocale);
	
			//each JSON Object "jsonObj" is a reference to a product
			json.forEach(function (jsonObj) {
				if(empty(jsonObj)) {
					continue;
				}
				//retrieve the locale specific product data from the JSON
				var localeJSON = jsonObj[currentLocale];
				//each key is a reference to a product attribute
				for (var key in localeJSON) {
					if (localeJSON.hasOwnProperty(key)) {
						localeFileWriter.write( localeJSON[key] );
						localeFileWriter.write("\t");
					}
				}
				localeFileWriter.write("\n");
			});
		});
	} catch (e) {
		Logger.error('ExportCatalog.js has failed on the write step with the following error: ' + e.message);
	}
} 

//function is executed only ONCE
function afterStep( success, parameters, stepExecution )
{
	try {
		//loop through all the locales and close each corresponding file writer
		allowedLocales.forEach(function () {
			//retrieve the current file writer
			var currLocaleFileWriter = hashMapOfFileWriters.get(currentLocale);
	
			if(!empty(currLocaleFileWriter)) {
				currLocaleFileWriter.close();
			}
		});
	} catch (e) {
		Logger.error('ExportCatalog.js has failed on the afterStep step with the following error: ' + e.message);
	}
}

module.exports = {
		beforeStep: beforeStep,
		getTotalCount: getTotalCount,
		read: read,
		process: process,
		write: write,
		afterStep: afterStep
	};
